version: '3'

services:
  app:
    container_name: rlcs_app
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${SECRET_ADMIN_APP_PORT}:${SECRET_ADMIN_APP_PORT}"
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - APP_PORT=${APP_PORT}
      - SECRET_ADMIN_APP_PORT=${SECRET_ADMIN_APP_PORT}
  ui:
    container_name: rlcs_ui
    build: ./ui
    ports:
      - "80:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: rlcs_elastic
#    networks:
#      - elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Des.cores=1"  # Set JVM options as needed
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "9200:9200"  # Elasticsearch HTTP
      - "9300:9300"  # Elasticsearch TCP
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    # Add other Elasticsearch configurations as needed

#networks:
#  elastic:
#    driver: bridge
