package com.wfbfm.rlcsbot.websocket;

public enum AdminCommand
{
    INVALID,
    DELETE_SERIES,
    DELETE_SERIES_EVENT,
    UPDATE_SERIES,
    UPDATE_SERIES_EVENT,
    LIQUIPEDIA_URL,
    BROADCAST_URL,
    START_BROADCAST,
    STOP_BROADCAST,
    DISPLAY_NAME,
    ALLOW_MIDSERIES,
    FLUSH_WEBSOCKET,
    SAMPLING_RATE,
    TRANSCRIPTION_WAIT,
    BEST_OF,
    GAME_WINNER,
    ABANDON_SERIES
}
