package com.wfbfm.rlcsbot.screenshotparser;

public enum SubImageType
{
    BLUE_GAME_SCORE,
    ORANGE_GAME_SCORE,
    BLUE_SERIES_TICK1,
    BLUE_SERIES_TICK2,
    BLUE_SERIES_TICK3,
    BLUE_SERIES_TICK4,
    ORANGE_SERIES_TICK1,
    ORANGE_SERIES_TICK2,
    ORANGE_SERIES_TICK3,
    ORANGE_SERIES_TICK4,
    BLUE_TEAM,
    ORANGE_TEAM,
    BLUE_PLAYER1,
    BLUE_PLAYER2,
    BLUE_PLAYER3,
    ORANGE_PLAYER1,
    ORANGE_PLAYER2,
    ORANGE_PLAYER3,
    CLOCK,
    BEST_OF,
    GAME_NUMBER,
    DESCRIPTION;
}
